all:	
	g++ client_part2.cpp -o cpart2
	g++ client_part3.cpp -o cpart3
	g++ client_part4.cpp -o cpart4
compile:
	g++ client_part2.cpp -o cpart2
	g++ client_part3.cpp -o cpart3
	g++ client_part4.cpp -o cpart4