all:	
	g++ server_part1.cpp -o spart1
	g++ server_part2.cpp -o spart2
	g++ server_part3.cpp -o spart3
	g++ server_part4.cpp -o spart4 -pthread -std=c++11
compile:
	g++ server_part1.cpp -o spart1
	g++ server_part2.cpp -o spart2
	g++ server_part3.cpp -o spart3
	g++ server_part4.cpp -o spart4 -pthread -std=c++11